name: Test

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: master

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main
    
      - name: Install Hyperfine
        run: cargo binstall -y hyperfine
    
      - name: Build
        run: make build

      - name: Run benchmarks
        run: make build-compare-benchmarks

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: master

      - name: Lint
        run: zig fmt --check src/*.zig

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: master

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Test
        run: |
          zig version
          make test

  integration_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Zig
        uses: korandoru/setup-zig@v1
        with:
          zig-version: master

      - name: Integration test
        run: |
          zig version
          make build-integration-test
          ./zig-out/bin/integration_test